import Header from './_lib/components/Header'
import './_lib/styles/globals.css'

export const metadata = {
  title: 'Omkar Panchal | Full Stack Developer',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
